# Add your integration-specific settings here

from environs import Env

env = Env()
env.read_env()

GFW_DATASET_QUERY_CONCURRENCY = env.int("GFW_DATASET_QUERY_CONCURRENCY", 5)
PROCESS_PUBSUB_MESSAGES_IN_BACKGROUND = env.bool("PROCESS_PUBSUB_MESSAGES_IN_BACKGROUND", False)

# Optimization settings
GFW_MAX_PARTITIONS_PER_AOI = env.int("GFW_MAX_PARTITIONS_PER_AOI", 10)
GFW_MAX_DAYS_PER_QUERY = env.int("GFW_MAX_DAYS_PER_QUERY", 7)
GFW_BATCH_CONCURRENCY_LIMIT = env.int("GFW_BATCH_CONCURRENCY_LIMIT", 5)
GFW_METADATA_CACHE_TTL = env.int("GFW_METADATA_CACHE_TTL", 3600)  # 1 hour
GFW_ENABLE_SMART_DATE_RANGES = env.bool("GFW_ENABLE_SMART_DATE_RANGES", True)
GFW_ENABLE_BATCH_PROCESSING = env.bool("GFW_ENABLE_BATCH_PROCESSING", True)
